### ISSUE TITLE
l2blocks download routine error on X Layer Mainnet using v1.1.0 

### ISSUE THREAD

**Issue by andreclaro** [0xPolygon/cdk-erigon#506] opened 2024-05-30 22:47 UTC
#### System information

Erigon version: `1.1.0`

OS & Version: Linux

Chain/Network:  X Layer Mainnet

#### Expected behaviour
No errors...

#### Actual behaviour
"l2blocks download routine error" using `v1.1.0`

#### Backtrace

````
May 30 22:35:38 m-xlayer-01 cdk-erigon[1053141]: [EROR] [05-30|22:35:38.183] Staged Sync                              err="[3/16 Batches] l2blocks download routine error: 10.86.0.124:34156 16.162.197.255:8800 Error sending to server: write tcp 10.86.0.124:34156->16.162.197.255:8800: write: broken pipe"
May 30 22:35:38 m-xlayer-01 cdk-erigon[1053141]: [INFO] [05-30|22:35:38.684] [3/16 Batches] Starting batches stage
May 30 22:35:38 m-xlayer-01 cdk-erigon[1053141]: [INFO] [05-30|22:35:38.684] [3/16 Batches] Starting stream           startBlock=0
May 30 22:35:38 m-xlayer-01 cdk-erigon[1053141]: [INFO] [05-30|22:35:38.685] [3/16 Batches] Reading blocks from the datastream.
May 30 22:35:38 m-xlayer-01 cdk-erigon[1053141]: [INFO] [05-30|22:35:38.685] [3/16 Batches] Started downloading L2Blocks routine
May 30 22:35:38 m-xlayer-01 cdk-erigon[1053141]: [INFO] [05-30|22:35:38.685] [3/16 Batches] Finished Batches stage
May 30 22:35:38 m-xlayer-01 cdk-erigon[1053141]: [EROR] [05-30|22:35:38.685] Error while executing stage              err="[3/16 Batches] l2blocks download routine error: 10.86.0.124:34156 16.162.197.255:8800 Error sending to server: write tcp 10.86.0.124:34156->16.162.197.255:8800: write: broken pipe"
May 30 22:35:38 m-xlayer-01 cdk-erigon[1053141]: [EROR] [05-30|22:35:38.685] Staged Sync                              err="[3/16 Batches] l2blocks download routine error: 10.86.0.124:34156 16.162.197.255:8800 Error sending to server: write tcp 10.86.0.124:34156->16.162.197.255:8800: write: broken pipe"
May 30 22:35:38 m-xlayer-01 cdk-erigon[1053141]: [INFO] [05-30|22:35:38.685] [3/16 Batches] Finished downloading L2Blocks routine
May 30 22:35:39 m-xlayer-01 cdk-erigon[1053141]: [INFO] [05-30|22:35:39.185] [3/16 Batches] Starting batches stage
May 30 22:35:39 m-xlayer-01 cdk-erigon[1053141]: [INFO] [05-30|22:35:39.185] [3/16 Batches] Starting stream           startBlock=0
May 30 22:35:39 m-xlayer-01 cdk-erigon[1053141]: [INFO] [05-30|22:35:39.185] [3/16 Batches] Reading blocks from the datastream.
May 30 22:35:39 m-xlayer-01 cdk-erigon[1053141]: [INFO] [05-30|22:35:39.185] [3/16 Batches] Started downloading L2Blocks routine
May 30 22:35:39 m-xlayer-01 cdk-erigon[1053141]: [INFO] [05-30|22:35:39.185] [3/16 Batches] Finished Batches stage
May 30 22:35:39 m-xlayer-01 cdk-erigon[1053141]: [EROR] [05-30|22:35:39.185] Error while executing stage              err="[3/16 Batches] l2blocks download routine error: 10.86.0.124:34156 16.162.197.255:8800 Error sending to server: write tcp 10.86.0.124:34156->16.162.197.255:8800: write: broken pipe"
May 30 22:35:39 m-xlayer-01 cdk-erigon[1053141]: [INFO] [05-30|22:35:39.185] [3/16 Batches] Finished downloading L2Blocks routine
May 30 22:35:39 m-xlayer-01 cdk-erigon[1053141]: [EROR] [05-30|22:35:39.185] Staged Sync                              err="[3/16 Batches] l2blocks download routine error: 10.86.0.124:34156 16.162.197.255:8800 Error sending to server: write tcp 10.86.0.124:34156->16.162.197.255:8800: write: broken pipe"
May 30 22:35:39 m-xlayer-01 cdk-erigon[1053141]: [INFO] [05-30|22:35:39.686] [3/16 Batches] Starting batches stage
May 30 22:35:39 m-xlayer-01 cdk-erigon[1053141]: [INFO] [05-30|22:35:39.687] [3/16 Batches] Starting stream           startBlock=0
May 30 22:35:39 m-xlayer-01 cdk-erigon[1053141]: [INFO] [05-30|22:35:39.687] [3/16 Batches] Reading blocks from the datastream.
May 30 22:35:39 m-xlayer-01 cdk-erigon[1053141]: [INFO] [05-30|22:35:39.687] [3/16 Batches] Started downloading L2Blocks routine
May 30 22:35:39 m-xlayer-01 cdk-erigon[1053141]: [INFO] [05-30|22:35:39.687] [3/16 Batches] Finished downloading L2Blocks routine
May 30 22:35:39 m-xlayer-01 cdk-erigon[1053141]: [INFO] [05-30|22:35:39.687] [3/16 Batches] Finished Batches stage
````

**Comment by mandrigin** [comment] 2024-05-31 13:58
1.1.x is not compatible with the legacy datastream, the datastream and the sequencer needs to be updated for that
its a painful procedure, but yeah, until you switch to the new datastream, you must use 1.0.x releases

**Comment by andreclaro** [comment] 2024-06-03 10:04
@giskook @mandrigin, so this will require an update in the X Layer sequencer and datastream first? and then node operator can update their clients?

**Comment by giskook** [comment] 2024-06-03 10:23
> @giskook @mandrigin, so this will require an update in the X Layer sequencer and datastream first? and then node operator can update their clients?

Yes, If want to use 1.1.x, the sequencer should be upgrade first.

**Comment by andreclaro** [comment] 2024-06-03 10:28
> Yes, If want to use 1.1.x, the sequencer should be upgrade first.

@giskook, Do you have any plans to update the sequencer? do you also need to update the datastream on your side?

**Comment by mandrigin** [comment] 2024-06-03 13:11
yeah, that was a painful process now, because old datastream format was un-upgradeable basically

now we have a much better version, based on Protobuf, but this upgrade should be unfortunately scheduled with the node operators

**Comment by andreclaro** [comment] 2024-06-03 13:37
does this update also affects node operators running other clients, like zkNode + Prover?

**Comment by mandrigin** [comment] 2024-06-03 14:58
Only those who run Erigon, no other components are using the datastream (yet).

**Comment by mandrigin** [comment] 2024-06-04 14:22
I will close it for now, since “it is not a bug, it is a feature”.

**Closed as completed by mandrigin** 2024-06-04 14:22 UTC
