### ISSUE TITLE
Delay on Bridges due to a delay on updating the GER in endpoint zkevm_getLatestGlobalExitRoot

### ISSUE THREAD

**Issue by ARR552** [0xPolygon/cdk-erigon#1381] opened 2024-10-30 09:53 UTC
Using the zkevm node, bridges used to take arround 10-15 minutes max but using erigon sequencer is taking 40-45 min. Probably erigon is waiting for ger to be finalized in L1 before using them in L2 blocks. The problem is that the fast finality and user experience is now really bad.

**Comment by V-Staykov** [comment] 2024-10-30 13:48
What type of blocks the node queries from L1 can be changed via the `zkevm.l1-highest-block-type` flag. The default value is indeed "finalized" and can be set if needed to "latest" or "safe".

Maybe it is a good idea to not change anything in the code and just config sequencer to use "latest" @mandrigin ?

**Comment by mandrigin** [comment] 2024-10-30 17:33
@V-Staykov I think the issue is not in that, is that we read L1 only between batches, so if the batch is not closed, we don't update GER.

**Comment by Sharonbc01** [comment] 2024-11-07 17:08
Hi @mandrigin can we close this issue as fixed on the CDK Erigon side with PR [1386](https://github.com/0xPolygonHermez/cdk-erigon/issues/1386)

Also can you confirm it is in v2.60.x for when we deploy to Bali?

**Comment by mandrigin** [comment] 2024-11-07 17:13
that is in 2.60 yes, we can close

**Closed as completed by mandrigin** 2024-11-07 17:13 UTC
Labels: Critical, Gateway FM
