### ISSUE TITLE
[Sequencer/RPC] Mismatch zkcounts by call  zkevm_estimateCounters between zkNode and Erigon

### ISSUE THREAD

**Issue by zjg555543** [0xPolygon/cdk-erigon#1231] opened 2024-09-26 11:22 UTC
I found some differents between zkNode and Erigon while calling zkevm_estimateCounters.
A little confused, so what is the reason about this?

Erigon: [v2.0.0-beta21](https://github.com/0xPolygonHermez/cdk-erigon/releases/tag/v2.0.0-beta21) (forkID9)
zkNode: [v0.7.3](https://github.com/0xPolygonHermez/zkevm-node/releases/tag/v0.7.3), [v6.0.2](https://github.com/0xPolygonHermez/zkevm-prover/releases/tag/v6.0.2)(forkID9)

1. start 2 private chains by erigon and zkNode separately
2. depoly ERC20 contract separately
3. call zkevm_estimateCounters with the function transfer
4. **got same gas, but different zkcounts**
![img_v3_02f3_1b386e52-bcc0-4114-91aa-9fa02c82775h](https://github.com/user-attachments/assets/72c1ad9c-fc5e-400f-961d-367de316616b)

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract SimpleERC20 {
    string public name = "SimpleToken";
    string public symbol = "STK";   
    uint8 public decimals = 18;    
    uint256 public totalSupply;  

    mapping(address => uint256) public balances;
    mapping(address => mapping(address => uint256)) public allowance;

    event Transfer(address indexed from, address indexed to, uint256 value);

    event Approval(address indexed owner, address indexed spender, uint256 value);

    constructor() {
        totalSupply = 10000000000 * (10 ** uint256(decimals)); 
        balances[msg.sender] = totalSupply; 
        emit Transfer(address(0), msg.sender, totalSupply); 
    }

    function transfer(address _to, uint256 _value) public returns (bool success) {
        require(_to != address(0), "Invalid address");
        require(balances[msg.sender] >= _value, "Insufficient balance");

        balances[msg.sender] -= _value;
        balances[_to] += _value; 

        emit Transfer(msg.sender, _to, _value);
        return true;
    }

    function approve(address _spender, uint256 _value) public returns (bool success) {
        allowance[msg.sender][_spender] = _value;
        emit Approval(msg.sender, _spender, _value); 
        return true;
    }

    function transferFrom(address _from, address _to, uint256 _value) public returns (bool success) {
        require(_to != address(0), "Invalid address");
        require(balances[_from] >= _value, "Insufficient balance");
        require(allowance[_from][msg.sender] >= _value, "Allowance exceeded");

        balances[_from] -= _value; 
        balances[_to] += _value;     
        allowance[_from][msg.sender] -= _value; 

        emit Transfer(_from, _to, _value);
        return true;
    }

    function getBalanceOf(address _owner) public view returns (uint256 balance) {
        return balances[_owner];
    }

    function getAllowance(address _owner, address _spender) public view returns (uint256 remaining) {
        return allowance[_owner][_spender];
    }
}

```

**Comment by V-Staykov** [comment] 2024-09-26 12:02
To compare the counters you should do it on one network with legacy and erigon nodes. There are a few reasons for that. One is that the SMT depth is used in the calculations. Another is that the tx execution might be different.

In this case I see that the memAligns are diffent and they are used only in memory manipulation during execution. Our node returns 0 so that leads me to think that the transaction was executed in a completely different way and no opCode with memory manipulation was used.

**Comment by zjg555543** [comment] 2024-09-27 02:09
Got it, thanks. Two more things to check:
1. Is the zkcount result returned by Erigon as expected?
2. Arbitrarily modifying the Erigon defaultTotalSteps(eg. modify to defaultTotalSteps * 2)  value maybe cause the prover verification to fail?

**Comment by zjg555543** [comment] 2024-09-27 02:21
Background:
The issue is that we can execute an AA transaction in a zkNode chain, but we cannot do so in Erigon because the zkcount limit has been exceeded.

Erigon aa tx cost steps: 46,169,013
Devnet aa tx cost steps: 6,371,526

**Comment by V-Staykov** [comment] 2024-09-27 07:03
```
1. Is the zkcount result returned by Erigon as expected?
2. Arbitrarily modifying the Erigon defaultTotalSteps(eg. modify to defaultTotalSteps * 2) value maybe cause the prover verification to fail?
```

1. We have tests to match tx counters to the commonJs implementation. The estimateCoutners endpoint hasn't been much tested I guess, so it mght have differences.

2. Modifying the total steps could definately make the prover fail, but on our side it is made to match the commonJs implementation as well. It is being changed byt forkId though, so there might be something there if the prover is on different forkid than the sequencer for example.

The difference you mention is huge and definately concerning. We'll have another look at it. Can you give us the Tx that reproduces this?

**Comment by V-Staykov** [comment] 2024-09-27 11:34
@zjg555543 just got some info from the team. Turns out legacy node counters are actual and since our counters are virtual, the big difference is expected. I am closing this ticket for now.

**Closed as completed by V-Staykov** 2024-09-27 11:34 UTC
Labels: bug
