### ISSUE TITLE
[RPC] getBatchByNumber - Issues (ts, ger, mer,rer)

### ISSUE THREAD

**Issue by revitteth** [0xPolygon/cdk-erigon#809] opened 2024-07-17 15:43 UTC
- Tx Ordering is off in some cases
- TimeStamp is wrong on Cardona (batch 59000 - https://cardona-zkevm.polygonscan.com/batch/59000)
- Mainnet exit root and rollup exit root wrong on Cardona 104708
- Batch checker script in debug_tools can be used to find more instances, and should be used to fix this

Also of note, Hermez team investigating issue with timestamp simultanously.

**Comment by Sharonbc01** [comment] 2024-07-30 18:01
@mandrigin is this a duplicate of #822

**Comment by revitteth** [comment] 2024-07-31 09:32
@Sharonbc01 afaics this is not a duplicate but some other noticed discrepancies. I'll catch up and update here in a bit though.

**Comment by Sharonbc01** [comment] 2024-07-31 11:31
Thanks @revitteth we are pushing to get RPC to mainnet so keen to close out as soon as possible please. Thanks

**Comment by revitteth** [comment] 2024-08-02 15:32
Update: 
- 'high water mark' verification and sequence txs are fixed rather than returning 0x00...00 we return the 'next highest sequence/verification' that we have - fixed
- datastream is pushing some out of order txs to the node. - not fixed
- it looks like both etherscan for cardona and the cdk-erigon node 'see the same thing' with regards to some batches - but the zkevm node returns differently with knowledge of L1 logs (for example: https://cardona-zkevm.polygonscan.com/batch/110809) - not fixed

**Comment by mandrigin** [comment] 2024-08-20 09:35
I think its good now, no issues syncing pless nodes for 4 days at least, closing this one

**Closed as completed by mandrigin** 2024-08-20 09:35 UTC
Labels: bug, Gateway FM
