### ISSUE TITLE
[RPC] stuck during syncing

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#1485] opened 2024-11-19 09:15 UTC
During syncing we see the batches stage getting stuck and beyond that it makes no progress.  The pattern appears as the image below:

![telegram-cloud-photo-size-5-6188431868307815870-y](https://github.com/user-attachments/assets/bb1c914e-3a4d-4c95-939d-840c81765477)

It looks as the though the stream client is missing some cleanup code at either the start of a new stage or at the end before the stage is completed.

**Comment by zjg555543** [comment] 2024-11-20 08:15
Detail logs: [cdk-error.log](https://github.com/user-attachments/files/17827258/cdk-error.log)


The `if err := r.connectDatastream(); err != nil` was been deleted, so we need to retry again while got an disconnect?

https://github.com/0xPolygonHermez/cdk-erigon/pull/1297/files#diff-c43323397404731c60022d8f8de469c44812cfa36b82ec7fd99dc429e1b5803eL40

**Comment by Vui-Chee** [comment] 2024-11-20 10:04
Just to add another thought to this discussion, in the implementation of StreamClient, whenever you read from the TCP connection (readBuffer), I noticed you set the read deadline (SetReadDeadline) for the connection. The issues we have seeing shows the error (i/o timeout).

Before you start reading full blocks, `net.Dial` is successful, meaning there is already a successful TCP connection to begin with, thereby the data stream client is successfully constructed. Is is possible the stream client may have prematurely shut down its TCP connection during the read process, thereby no further entries are written to `entryChan` (causing batch process loop to stall)?

**Comment by hexoscott** [comment] 2024-11-20 10:14
Hi @Vui-Chee - this has been a long journey on the stream client.  Certain calls to the datastream host will terminate the connection unexpectedly and we get occasional drops due to inactivity etc. We're continuing to investigate

**Comment by ToniRamirezM** [comment] 2024-11-21 07:07
Regarding the inactivity, check you have set a value for `InactivityTimeout` and `InactivityCheckInterval`

https://github.com/0xPolygon/zkevm-data-streamer/blob/main/datastreamer/config.go#L18

**Comment by giskook** [comment] 2024-11-21 07:18
> Regarding the inactivity, check you have set a value for `InactivityTimeout` and `InactivityCheckInterval`

Our data-streamer are on [v0.2.3-RC4](https://github.com/0xPolygon/zkevm-data-streamer/releases/tag/v0.2.3-RC4)
So we do not have such configuration yet

**Comment by hexoscott** [comment] 2024-11-21 09:29
There is a fix inbound for this, just going through CI now

**Comment by hexoscott** [comment] 2024-11-21 09:30
Ref: #1492

**Comment by giskook** [comment] 2024-11-21 09:35
> Ref: #1492

Cool, many thanks, I will try this fix.

**Comment by giskook** [comment] 2024-11-23 11:40
Based on this fix, it sometimes allows normal recovery, but it ultimately still leads to being stuck.
```
[INFO] [11-23|04:14:09.341] [15/15 Finish] Finished
[INFO] [11-23|04:14:09.341] Timings (slower than 50ms)               L1InfoTree=95ms Batches=55ms alloc=207.0MB sys=4.8GB
[INFO] [11-23|04:14:09.341] [1/15 L1Syncer] Starting L1 sync stage
[INFO] [11-23|04:14:09.341] [1/15 L1Syncer] No new L1 blocks to sync
[INFO] [11-23|04:14:09.341] [1/15 L1Syncer] Finished L1 sync stage
[INFO] [11-23|04:14:09.341] [2/15 L1InfoTree] Starting L1 Info Tree stage
[INFO] [11-23|04:14:09.387] [2/15 L1InfoTree] Info tree updates      count=0 latestIndex=49771
[INFO] [11-23|04:14:09.387] [2/15 L1InfoTree] Finished L1 Info Tree stage
[INFO] [11-23|04:14:09.387] [3/15 Batches] Starting batches stage
[INFO] [11-23|04:14:12.530] [3/15 Batches] Highest block in datastream datastreamBlock=6801270 stageProgressBlockNo=6801269
[INFO] [11-23|04:14:12.530] [3/15 Batches] Reading blocks from the datastream.
[INFO] [11-23|04:14:12.531] [3/15 Batches] Started downloading L2Blocks routine ID: 163112
[WARN] [11-23|04:14:19.335] readAllFullL2BlocksToChannel: NextFileEntry: readBuffer: socket error: io.ReadFull: read tcp 172.21.4.17:51116->18.163.17.131:8800: i/o timeout
[INFO] [11-23|04:14:22.530] [3/15 Batches] Downloaded blocks from datastream progress: 5
[WARN] [11-23|04:14:25.377] readAllFullL2BlocksToChannel: NextFileEntry: readBuffer: socket error: io.ReadFull: read tcp 172.21.4.17:42054->16.162.197.255:8800: i/o timeout
[WARN] [11-23|04:14:31.425] readAllFullL2BlocksToChannel: NextFileEntry: readBuffer: socket error: io.ReadFull: read tcp 172.21.4.17:19764->18.166.142.150:8800: i/o timeout
[INFO] [11-23|04:14:32.530] [3/15 Batches] Downloaded blocks from datastream progress: 8
[WARN] [11-23|04:14:37.579] readAllFullL2BlocksToChannel: NextFileEntry: readBuffer: socket error: io.ReadFull: read tcp 172.21.4.17:60618->18.163.17.131:8800: i/o timeout
[INFO] [11-23|04:14:42.531] [3/15 Batches] Downloaded blocks from datastream progress: 11
[WARN] [11-23|04:14:43.523] readAllFullL2BlocksToChannel: NextFileEntry: readBuffer: socket error: io.ReadFull: read tcp 172.21.4.17:42008->16.162.197.255:8800: i/o timeout
[WARN] [11-23|04:14:49.676] readAllFullL2BlocksToChannel: NextFileEntry: readBuffer: socket error: io.ReadFull: read tcp 172.21.4.17:15074->18.166.142.150:8800: i/o timeout
[INFO] [11-23|04:14:52.531] [3/15 Batches] Downloaded blocks from datastream progress: 15
[WARN] [11-23|04:14:58.850] readAllFullL2BlocksToChannel: NextFileEntry: readBuffer: socket error: io.ReadFull: read tcp 172.21.4.17:16650->18.163.17.131:8800: i/o timeout
[INFO] [11-23|04:15:02.531] [3/15 Batches] Downloaded blocks from datastream progress: 18
[WARN] [11-23|04:15:04.807] readAllFullL2BlocksToChannel: NextFileEntry: readBuffer: socket error: io.ReadFull: read tcp 172.21.4.17:46448->16.162.197.255:8800: i/o timeout
[INFO] [11-23|04:15:05.941] [p2p] GoodPeers
[INFO] [11-23|04:15:06.213] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=219.5MB sys=4.8GB
[INFO] [11-23|04:15:06.516] [mem] memory stats                       Rss=44.0GB Size=0B Pss=44.0GB SharedClean=2.1MB SharedDirty=0B PrivateClean=42.2GB PrivateDirty=1.9GB Referenced=43.5GB Anonymous=1.9GB Swap=0B alloc=219.5MB sys=4.8GB
[WARN] [11-23|04:15:10.855] readAllFullL2BlocksToChannel: NextFileEntry: readBuffer: socket error: io.ReadFull: read tcp 172.21.4.17:9956->18.163.17.131:8800: i/o timeout
[INFO] [11-23|04:15:12.531] [3/15 Batches] Downloaded blocks from datastream progress: 21
[WARN] [11-23|04:15:20.040] readAllFullL2BlocksToChannel: NextFileEntry: readBuffer: socket error: io.ReadFull: read tcp 172.21.4.17:53516->16.162.197.255:8800: i/o timeout
[WARN] [11-23|04:15:20.156] [3/15 Batches] Error downloading blocks from datastream error="readAllEntriesToChannel: initiateDownloadBookmark: afterStartCommand: readResultEntry: invalid starting bookmark: Bad from bookmark"
[INFO] [11-23|04:15:20.156] [3/15 Batches] Ended downloading L2Blocks routine ID: 163112
[INFO] [11-23|04:15:22.531] [3/15 Batches] Downloaded blocks from datastream progress: 23
[INFO] [11-23|04:15:32.531] [3/15 Batches] Downloaded blocks from datastream progress: 23
[INFO] [11-23|04:15:42.531] [3/15 Batches] Downloaded blocks from datastream progress: 23
[INFO] [11-23|04:15:52.531] [3/15 Batches] Downloaded blocks from datastream progress: 23
[INFO] [11-23|04:16:02.531] [3/15 Batches] Downloaded blocks from datastream progress: 23
[INFO] [11-23|04:16:12.531] [3/15 Batches] Downloaded blocks from datastream progress: 23
[INFO] [11-23|04:16:22.530] [3/15 Batches] Downloaded blocks from datastream progress: 23
```

**Comment by giskook** [comment] 2024-11-24 08:38
Another interseting log
```
[INFO] [11-24|07:25:50.834] [2/15 L1InfoTree] Info tree updates      count=0 latestIndex=49862
[INFO] [11-24|07:25:50.834] [2/15 L1InfoTree] Finished L1 Info Tree stage
[INFO] [11-24|07:25:50.834] [3/15 Batches] Starting batches stage
[WARN] [11-24|07:25:50.890] [3/15 Batches] Failed to get latest l2 block from datastream: getLatestL2Block: GetHeader: readResultEntry: client already started: Already started
[INFO] [11-24|07:25:50.890] [3/15 Batches] Finished Batches stage
[INFO] [11-24|07:25:50.890] [6/15 Execution] Blocks execution        from=6833549 to=6833549
```
... ...
```
[INFO] [11-24|07:25:56.386] [3/15 Batches] Highest block in datastream datastreamBlock=6833550 stageProgressBlockNo=6833549
[INFO] [11-24|07:25:56.386] [3/15 Batches] Reading blocks from the datastream.
[INFO] [11-24|07:25:56.387] [3/15 Batches] Started downloading L2Blocks routine ID: 627785
[WARN] [11-24|07:25:56.513] [3/15 Batches] Error downloading blocks from datastream error="readAllEntriesToChannel: readAllFullL2BlocksToChannel: unexpected entry type: &{6833550}"
[INFO] [11-24|07:25:56.513] [3/15 Batches] Ended downloading L2Blocks routine ID: 627785
[INFO] [11-24|07:26:06.387] [3/15 Batches] Downloaded blocks from datastream progress: 1
[INFO] [11-24|07:26:16.387] [3/15 Batches] Downloaded blocks from datastream progress: 1
```

**Comment by Vui-Chee** [comment] 2024-11-25 03:59
There is another case where the RPC also gets stuck. After parsing proto, it encountered unexpected entry type error (not socket error), the main go routine for reading entries will terminate. Once routine stops, no further entries are read.
<img width="1717" alt="Screenshot 2024-11-25 at 11 54 06 AM" src="https://github.com/user-attachments/assets/343cfcc8-79f2-4d1d-87bc-1390cf4f469d">

**Comment by Vui-Chee** [comment] 2024-11-25 04:42
From my understanding, in the function `readAllFullL2BlocksToChannel`, after the first `ReadParsedProto()` call, the case `*types.L2BlockEndProto` is not being handled in the switch statement, resulting in the error log `fmt.Errorf("unexpected entry type: %v", parsedProto)` being printed. I say this because the only way to print out `&{6833550}` is to match some type.

**Comment by Sharonbc01** [comment] 2024-11-25 16:45
Confirmed fixed in Rc4

**Closed as completed by Sharonbc01** 2024-11-25 16:45 UTC
Labels: bug
