### ISSUE TITLE
[Datastream] Some `batchStart` entries in the Cardona datastream have `forkId` not set

### ISSUE THREAD

**Issue by V-Staykov** [0xPolygon/cdk-erigon#1036] opened 2024-08-27 09:06 UTC
Chain/Network:  Cardona

#### Expected behaviour
All `batchStart` entries should have forkid set.

#### Actual behaviour
On Cardona stream `datastream.cardona.zkevm-rpc.com:6900` some blocks have `forkId` of 0. Examples are the batch starts for batches: 7, 49

These coincide with empty batches (no blocks), so this may be connected

**Comment by hexoscott** [comment] 2024-09-20 09:47
This is now fixed, caused by us not writing the fork for an empty batch.  We now fall back to the previous batch fork id when populating the stream.

**Closed as completed by hexoscott** 2024-09-20 09:47 UTC
